name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Secrets
      uses: bitwarden/sm-action@v1
      with:
        access_token: ${{ secrets.BW_ACCESS_TOKEN }}
        base_url: https://vault.bitwarden.eu
        secrets: |
          9daacb93-c531-467d-a26b-b147008919ee > DOCKER_USERNAME
          812e5bc9-a062-438f-9467-b1470088ee32 > DOCKER_PASSWORD
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        
  # push_to_docker:
  #     needs: build
  #     runs-on: ubuntu-latest
      
  #     steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: "${{ needs.build.outputs.DOCKER_USERNAME }}"
  #         password: "${{ needs.build.outputs.DOCKER_PASSWORD }}"
      
  #     - name: Build Docker image
  #       run: docker build -t keithhubner/klbc:latest .
      
  #     - name: Push Docker image to Docker Hub
  #       run: docker push keithhubner/klbc:latest
